<!DOCTYPE html>
<html>
<head>
  <title>Books</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://js.stripe.com/v3/"></script>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <header>
    <h1>Books</h1>
  </header>
  <main>
    <form id="search-form">
      <label for="language">Select Language:</label>
      <select name="language" id="language">
        <option value="all">All Languages</option>
        <option value="english">English</option>
        <option value="urdu">Urdu</option>
        <option value="hindi">Hindi</option>
        <option value="chinese">Chinese</option>
        <option value="japanese">Japanese</option>
        <option value="arabic">Arabic</option>
        <option value="persian">Persian</option>
        <option value="other">Other</option>
      </select>
      <label for="country">Select Country:</label>
      <select name="country" id="country">
        <option value="all">All Countries</option>
        <option value="united-states">United States</option>
        <option value="united-kingdom">United Kingdom</option>
        <option value="canada">Canada</option>
        <option value="australia">Australia</option>
        <option value="india">India</option>
        <option value="pakistan">Pakistan</option>
        <option value="china">China</option>
        <option value="other">Other</option>
      </select>
      <input type="submit" value="Search">
    </form>
    <section id="book-list">
    </section>
  </main>
  <script>
    // Initialize Stripe.js
    var stripe = Stripe('YOUR_PUBLISHABLE_KEY');
    $(document).ready(function() {
      $("#search-form").submit(function(e) {
        e.preventDefault();
        var language = $("#language").val();
        var country = $("#country").val();
        $.get("/books?language=" + language + "&country=" + country, function(data) {
          $("#book-list").html("");
          data.forEach(function(book) {
            var bookEl = $("<div class='book'></div>");
            var titleEl = $("<h2>" + book.title + "</h2>");
            var authorEl = $("<p>By " + book.author + "</p>");
            var downloadEl = $("<a href='" + book.download_link + "'>Download</a>");
            var readEl = $("<a href='"
